/**
 * Generated by scripts/build-manifest.mjs. Do not edit by hand.
 *
 * Just enough for the shell to render the Practice tab, its done/total count, and the rung
 * stepper, without pulling in the checks, solutions, and broken variants that make up the
 * bulk of the content. Run `npm run build:manifest` after changing an exercise set;
 * `npm run verify` fails if this has drifted.
 */

export interface ManifestRung {
  id: string;
  role: 'recognize' | 'guided' | 'implement' | 'break' | 'apply' | 'articulate';
  title: string;
  kind: 'choice' | 'expr' | 'code' | 'reveal';
}

export interface ManifestEntry {
  termId: string;
  /** Teaching this repo owns, rendered in Learn after the upstream entry. */
  notes: string | null;
  rungs: ManifestRung[];
}

export const manifest: ManifestEntry[] = [
  {
    "termId": "function",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which one is a function in the strict sense?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Relate every input to exactly one output",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "arity",
    "notes": "The glossary entry covers the names. The part that catches people out is that\nJavaScript has two different notions of arity, and `fn.length` reports the one you probably\ndid not mean.\n\n**Declared arity** is what `fn.length` gives you: the number of parameters written before\nthe first one that has a default or a rest. **Call arity** is how many arguments a particular\ncall actually passes, which `arguments.length` would tell you inside the function.\n\nThree rules decide what `fn.length` counts:\n\n- Counting **stops at the first parameter with a default**, and everything after it is\n  ignored, even parameters that have no default of their own. So `(a = 1, b) => 0` has a\n  length of 0, not 1.\n- A **rest parameter is never counted**. `(...xs) => 0` has a length of 0, which means a\n  variadic function and a nullary one look identical to `fn.length`.\n- A **destructured parameter is still one parameter**. `({ a, b }) => 0` has a length of 1.\n\nThis matters well beyond trivia, because [auto-currying](#auto-currying) decides how many\narguments to wait for by reading `fn.length`. Curry a variadic function and it will call\nthrough immediately, having been told the function takes nothing.",
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does fn.length actually count?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Name an arity",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "lambda",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What makes something a lambda?",
        "kind": "choice"
      },
      {
        "id": "guided",
        "role": "guided",
        "title": "Inline the named callbacks",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "higher-order-functions-hof",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Write filter and is",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Write once",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "closure",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A counter with private state",
        "kind": "code"
      },
      {
        "id": "break",
        "role": "break",
        "title": "Fix the loop that captured the wrong thing",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "predicate",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Combine predicates",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Build a filter from the pieces",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "pure-function",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which one is pure?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Purify addItem",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "thunk",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Defer the work",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Compute it at most once",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "partial-function",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which of these are partial?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Find the inputs that break it",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "total-function",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Make three functions total",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What makes a function total?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "trampoline",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Bounce instead of recursing",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Why does a trampoline help?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "partial-application",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Write partial",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Build fivePlus",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "currying",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Spot the curried functions",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Write curry2",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Go point-free",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "auto-currying",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Curry any function automatically",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Where does auto-currying stop working?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "function-composition",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Write compose and pipe",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Read a name out of a record",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "point-free-style",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which definitions are point-free?",
        "kind": "choice"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Remove the arguments",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "functional-combinator",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "The classic combinators",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What disqualifies a combinator?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "continuation",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Convert to continuation-passing style",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What is the continuation?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "lazy-evaluation",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "An infinite list you can take from",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Filter an endless list",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "io",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "An IO that does nothing until you run it",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Describe a program without running it",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "algebraic-effects",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Write the handler",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does the program know?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "side-effects",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Spot every effect",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Push the effects to the edge",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "value",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What can be a value?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Treat a function as data",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "constant",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does const actually promise?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Freeze all the way down",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "constant-function",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Write constant",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Use it to blank a list",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "referential-transparency",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which calls can be replaced by their result?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Make the calls substitutable",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "equational-reasoning",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which rewrites are safe?",
        "kind": "choice"
      },
      {
        "id": "guided",
        "role": "guided",
        "title": "Rewrite a pipeline step by step",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "idempotence",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which of these are idempotent?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Make normalizeEmail idempotent",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "memoization",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Cache by argument",
        "kind": "code"
      },
      {
        "id": "break",
        "role": "break",
        "title": "Watch memoization lie",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "contracts",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Wrap a function in a contract",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What is a contract for?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "type-signatures",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which implementation fits the signature?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Write the functions the signatures describe",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "algebraic-data-type",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Sum or product?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Count the inhabitants",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "product-type",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "How many values does this type have?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Build every inhabitant",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "sum-type",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A tagged union with an exhaustive match",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which of these are sum types?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "option",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Some, None, and the three ways out",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Read a nested field safely",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "either",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Left, Right, and fold",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "A parse pipeline that reports why it failed",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "lens",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "lens, view, set, over",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Update something nested",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "prism",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A prism for integers in strings",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Lens or prism?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "iso",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Two views of the same thing",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which pairs are isomorphisms?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "traversal",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Focus on many things at once",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "How many does each optic focus on?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "lambda-calculus",
    "notes": null,
    "rungs": [
      {
        "id": "guided",
        "role": "guided",
        "title": "Numbers made only of functions",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What is the lambda calculus made of?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "setoid",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Equality you can rely on",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which law does this break?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "semigroup",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Three ways to combine two things",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which operations are associative?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "monoid",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A semigroup with a neutral element",
        "kind": "code"
      },
      {
        "id": "break",
        "role": "break",
        "title": "Subtraction is not even a semigroup",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "functor",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Give Box a lawful map",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "A Maybe that skips missing values",
        "kind": "code"
      },
      {
        "id": "break",
        "role": "break",
        "title": "Break a law on purpose",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "pointed-functor",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A functor that knows how to lift",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What is of allowed to do?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "constant-functor",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A functor whose map does nothing",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What is Const good for?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "constant-monad",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A chain that keeps the contents",
        "kind": "code"
      },
      {
        "id": "break",
        "role": "break",
        "title": "Show that it is not a lawful monad",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "lift",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Lift an ordinary function into a container",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does lifting need from the container?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "applicative-functor",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Apply a wrapped function to a wrapped value",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Combine two Maybes without unwrapping either",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "monad",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "chain for Maybe",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "chain for Array",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "kleisli-composition",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Compose functions that return containers",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Why not ordinary composition?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "comonad",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "extract and extend",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Monad or comonad?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "free-monad",
    "notes": null,
    "rungs": [
      {
        "id": "apply",
        "role": "apply",
        "title": "Add an instruction to the program",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does \"free\" buy you?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "monad-transformer",
    "notes": null,
    "rungs": [
      {
        "id": "apply",
        "role": "apply",
        "title": "Stack Maybe on top of another monad",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Why do transformers exist?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "bifunctor",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Map over both slots",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "bimap for Either",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "contravariant-functor",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Map over the input instead of the output",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which way does composition go?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "profunctor",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Adjust both ends of a function",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which end is which?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "alternative",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Fall back to the other one",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Try several sources in order",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "foldable",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Fold a tree down to one value",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does Foldable let you write once?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "traversable",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Turn the structure inside out",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "traverse in one pass",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "morphism",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Objects and arrows",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Classify the arrows",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "semigroupoid",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Composition that associates",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Semigroupoid or category?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "category",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Composition with an identity",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What makes a category?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "endomorphism",
    "notes": null,
    "rungs": [
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which of these are endomorphisms?",
        "kind": "choice"
      },
      {
        "id": "implement",
        "role": "implement",
        "title": "Endomorphisms form a monoid",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "isomorphism",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A pair of morphisms that undo each other",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What makes it an isomorphism rather than two functions?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "homomorphism",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A map that preserves the structure",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which of these are homomorphisms?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "natural-transformation",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Change the container, not the contents",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does naturality forbid?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "catamorphism",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Collapse a structure to a value",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which direction?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "anamorphism",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "Build a structure from a seed",
        "kind": "code"
      },
      {
        "id": "apply",
        "role": "apply",
        "title": "Unfold the digits of a number",
        "kind": "code"
      }
    ]
  },
  {
    "termId": "hylomorphism",
    "notes": null,
    "rungs": [
      {
        "id": "apply",
        "role": "apply",
        "title": "Unfold then fold",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Why name it at all?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "paramorphism",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "A fold that can see what is left",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "What does para add?",
        "kind": "choice"
      }
    ]
  },
  {
    "termId": "apomorphism",
    "notes": null,
    "rungs": [
      {
        "id": "implement",
        "role": "implement",
        "title": "An unfold that can finish early",
        "kind": "code"
      },
      {
        "id": "recognize",
        "role": "recognize",
        "title": "Which unfold is which?",
        "kind": "choice"
      }
    ]
  }
];

export const manifestByTerm: Record<string, ManifestEntry> = Object.fromEntries(
  manifest.map((entry) => [entry.termId, entry]),
);

export const manifestTermIds: string[] = manifest.map((entry) => entry.termId);

export const hasExercises = (termId: string): boolean => termId in manifestByTerm;
